version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: flashcards_user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - flashcards_db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  flashcards_db_data: